services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8090:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      # 避免容器内自动生成 settings.yml 覆盖
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    restart: unless-stopped
    # 添加网络配置，允许本地访问
    network_mode: "bridge"


