# Test your FastAPI endpoints

GET http://127.0.0.1:8848/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

### deepsearch ok
POST http://127.0.0.1:8848/agent/deepsearch?query=今日新闻
Accept: application/json