from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Protocol


class UserRepository(Protocol):
    def upsert(self, user: Mapping[str, Any]) -> None: ...

    def delete(self, user_id: str) -> bool: ...


class CourseRepository(Protocol):
    def upsert(self, course: Mapping[str, Any]) -> None: ...

    def delete(self, course_id: str) -> bool: ...

    def get(self, course_id: str) -> dict[str, Any] | None: ...

    def list(self) -> list[dict[str, Any]]: ...

    def get_by_course_code(self, course_code: str) -> dict[str, Any] | None: ...


class CourseMembershipRepository(Protocol):
    def upsert(self, membership: Mapping[str, Any]) -> None: ...

    def delete(self, course_id: str, user_id: str) -> bool: ...
